services:
  - type: web
    name: speech-analyser
    env: ubuntu
    buildCommand: apt-get update && apt-get install -y php php-cli python3 python3-pip
    startCommand: php -S 0.0.0.0:10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
